language: python
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=flake8
install:
  - pip install tox pip<=5.99.99
script:
  - tox -e $TOX_ENV
notifications:
  irc: "chat.freenode.net#python-scotland"
  on_success: change
  on_failure: change
